### ISSUE TITLE
The performance of OA of ModelNet40

### ISSUE THREAD

**Issue by yechaowang** [hkust-vgd/shellnet#17]
I'm doing a comparative experiment about different Pointcloud framework recently. I only get the oa of 92.1% by Shellnet ,but it's 93.1% in the paper.

eval acc (oa): 0.920989 ---- eval acc (mean class): 0.879494 ---- time cost: 9.074277

used default setting with ss=16,bacth_size=32,and with multi=True

So,I wonder which results should I choose to report.... looking for your reply

**Comment by cszyzhang** [comment]
93.1%

**Comment by yechaowang** [comment]
> 93.1%

Yeah,I see you put the pre_trained model, thank a lot for your reply!
