### ISSUE TITLE
Issues with semantic3d_merge.py

### ISSUE THREAD

**Issue by ninasinger** [hkust-vgd/shellnet#9]
I am trying to visualize the labels returned in the "results/*.txt" from the semantic3d_merge.py. However, it seems that the labels do not correspond to the original order of the txt files used as the input to "data_conversions/prepare_semantic3d_data.py" . Can you give me some information about how to pair the final labels with their original x,y,z coordinates?

**Comment by longmalongma** [comment]
> I am trying to visualize the labels returned in the "results/*.txt" from the semantic3d_merge.py. However, it seems that the labels do not correspond to the original order of the txt files used as the input to "data_conversions/prepare_semantic3d_data.py" . Can you give me some information about how to pair the final labels with their original x,y,z coordinates?

@maptastic Hi,have your solved this problem?

**Comment by ninasinger** [comment]
@longmalongma No unfortunately,  I was only able to view and calculate the results by batch

**Comment by longmalongma** [comment]
> @longmalongma No unfortunately, I was only able to view and calculate the results by batch



> @longmalongma No unfortunately, I was only able to view and calculate the results by batch

＠maptastic Do you mean you can get mIoU and OA on the Semantic3D dataset? But you can't visualize the segmentation, right?
